/*
 * CanMessageFormat.h
 *
 * Created: 06.11.2015 09:07:02
 *  Author: sverrevr
 */ 


#ifndef CANMESSAGEFORMAT_H_
#define CANMESSAGEFORMAT_H_



#define CANMSG_PACKAGESPECIFIER 0

#define CANMSG_BTNR_BYTE 1
#define CANMSG_BTNR_BIT 0
#define CANMSG_SLIDERR_BYTE 2
#define CANMSG_JSX_BYTE 3
#define CANMSG_MOTORSIGNAL_LEN 4

#define PACKAGESPECIFIER_MOTORSIGNALS 0x00
#define PACKAGESPECIFIER_GAMEMODE 0x01
#define GAMEMODE_MODE_BYTE 1
#define GAMEMODE_OFF 0x0
#define GAMEMODE_JS 0x1
#define GAMEMODE_SENS 0x2
#define GAMEMODE_MSGLEN 2

#define PACKAGESPECIFIER_GAMEPOINT 0x02

#endif /* CANMESSAGEFORMAT_H_ */